#ifndef COMMANDS_H
#define COMMANDS_H

#define DELIM					" "
#define NEW					"\n"

#define CONSTRUCTION_CMD			"/construction/"
#define WORLD_CMD				"world/"
#define DETECTOR_CMD				"detector/"
#define ATOMIC_NUMBER_CMD			"atomicNumber"
#define NUMBER_DENSITY_CMD			"numberDensity"
#define TEMPERATURE_CMD				"temperature"
#define RADIUS_CMD				"radius"
#define THICKNESS_CMD				"thickness"
#define DEAD_LAYER_CMD				"deadLayer"

#define GENERATOR_CMD				"/generator/"
#define PRIMARY_CMD				"primary/"
#define SECONDARY_CMD				"secondary/"
#define PARTICLE_CMD				"particle"
#define ENERGY_CMD				"energy"
#define THETA_CMD				"theta"
#define DISTANCE_CMD				"distance"
#define NUMBER_CMD				"number"

#define ANALYSIS_CMD				"/analysis/"
#define FILE_CMD				"file"
#define	TITLE_CMD				"title"
#define BINS_CMD				"bins"
#define	MIN_CMD					"min"
#define	MAX_CMD					"max"

#define CUT_CMD					"/cuts"
#define LOW_ENERGY_CMD				"/setLowEdge"

#define RUN_CMD					"/run/"
#define THREADS_CMD				"numberOfThreads"
#define INIT_CMD				"initialize"
#define BEAM_ON_CMD				"beamOn"

#define CONTROL_CMD				"/control/"
#define EXECUTE_CMD				"execute"

#define MACRO_CMD				CONTROL_CMD		EXECUTE_CMD
#define ANALYSIS_FILE_CMD			ANALYSIS_CMD		FILE_CMD
#define WORLD_RADIUS_CMD			CONSTRUCTION_CMD	WORLD_CMD	RADIUS_CMD
#define DETECTOR_ATOMIC_NUMBER_CMD		CONSTRUCTION_CMD	DETECTOR_CMD	ATOMIC_NUMBER_CMD
#define DETECTOR_NUMBER_DENSITY_CMD		CONSTRUCTION_CMD	DETECTOR_CMD	NUMBER_DENSITY_CMD
#define DETECTOR_TEMPERATURE_CMD		CONSTRUCTION_CMD	DETECTOR_CMD	TEMPERATURE_CMD
#define DETECTOR_RADIUS_CMD			CONSTRUCTION_CMD	DETECTOR_CMD	RADIUS_CMD
#define DETECTOR_THICKNESS_CMD			CONSTRUCTION_CMD	DETECTOR_CMD	THICKNESS_CMD
#define DETECTOR_DEAD_LAYER_CMD			CONSTRUCTION_CMD	DETECTOR_CMD	DEAD_LAYER_CMD
#define GENERATOR_PRIMARY_PARTICLE_CMD		GENERATOR_CMD		PRIMARY_CMD	PARTICLE_CMD
#define GENERATOR_PRIMARY_ENERGY_CMD		GENERATOR_CMD		PRIMARY_CMD	ENERGY_CMD
#define GENERATOR_PRIMARY_DISTANCE_CMD		GENERATOR_CMD		PRIMARY_CMD	DISTANCE_CMD

#define ANALYSIS_PRIMARY_ENERGY_TITLE_CMD	ANALYSIS_CMD		PRIMARY_CMD	ENERGY_CMD	TITLE_CMD
#define ANALYSIS_PRIMARY_ENERGY_BINS_CMD	ANALYSIS_CMD		PRIMARY_CMD	ENERGY_CMD	BINS_CMD
#define ANALYSIS_PRIMARY_ENERGY_MIN_CMD		ANALYSIS_CMD		PRIMARY_CMD	ENERGY_CMD	MIN_CMD
#define ANALYSIS_PRIMARY_ENERGY_MAX_CMD		ANALYSIS_CMD		PRIMARY_CMD	ENERGY_CMD	MAX_CMD
#define ANALYSIS_PRIMARY_THETA_TITLE_CMD	ANALYSIS_CMD		PRIMARY_CMD	THETA_CMD	THETA_CMD
#define ANALYSIS_PRIMARY_THETA_BINS_CMD		ANALYSIS_CMD		PRIMARY_CMD	THETA_CMD	BINS_CMD
#define ANALYSIS_PRIMARY_THETA_MIN_CMD		ANALYSIS_CMD		PRIMARY_CMD	THETA_CMD	MIN_CMD
#define ANALYSIS_PRIMARY_THETA_MAX_CMD		ANALYSIS_CMD		PRIMARY_CMD	THETA_CMD	MAX_CMD
#define ANALYSIS_SECONDARY_TITLE_CMD		ANALYSIS_CMD		SECONDARY_CMD	NUMBER_CMD	TITLE_CMD
#define ANALYSIS_SECONDARY_BINS_CMD		ANALYSIS_CMD		SECONDARY_CMD	NUMBER_CMD	BINS_CMD
#define ANALYSIS_SECONDARY_MIN_CMD		ANALYSIS_CMD		SECONDARY_CMD	NUMBER_CMD	MIN_CMD
#define ANALYSIS_SECONDARY_MAX_CMD		ANALYSIS_CMD		SECONDARY_CMD	NUMBER_CMD	MAX_CMD
#define ANALYSIS_SECONDARY_ENERGY_TITLE_CMD	ANALYSIS_CMD		SECONDARY_CMD	ENERGY_CMD	TITLE_CMD
#define ANALYSIS_SECONDARY_ENERGY_BINS_CMD	ANALYSIS_CMD		SECONDARY_CMD	ENERGY_CMD	BINS_CMD
#define ANALYSIS_SECONDARY_ENERGY_MIN_CMD	ANALYSIS_CMD		SECONDARY_CMD	ENERGY_CMD	MIN_CMD
#define ANALYSIS_SECONDARY_ENERGY_MAX_CMD	ANALYSIS_CMD		SECONDARY_CMD	ENERGY_CMD	MAX_CMD
#define ANALYSIS_SECONDARY_THETA_TITLE_CMD	ANALYSIS_CMD		SECONDARY_CMD	THETA_CMD	THETA_CMD
#define ANALYSIS_SECONDARY_THETA_BINS_CMD	ANALYSIS_CMD		SECONDARY_CMD	THETA_CMD	BINS_CMD
#define ANALYSIS_SECONDARY_THETA_MIN_CMD	ANALYSIS_CMD		SECONDARY_CMD	THETA_CMD	MIN_CMD
#define ANALYSIS_SECONDARY_THETA_MAX_CMD	ANALYSIS_CMD		SECONDARY_CMD	THETA_CMD	MAX_CMD
#define CUT_LOW_ENERGY_CMD			CUT_CMD			LOW_ENERGY_CMD

#define RUN_THREADS_CMD				RUN_CMD			THREADS_CMD	NEW		RUN_CMD			INIT_CMD
#define RUN_SIMULATION_CMD			RUN_CMD			BEAM_ON_CMD

#endif
