#ifndef COMMANDS_H
#define COMMANDS_H

#define DELIM					" "
#define NEW					"\n"

#define GEOMETRY_CMD				"/geometry"
#define WORLD_CMD				"/world"
#define DETECTOR_CMD				"/detector"
#define ATOMIC_NUMBER_CMD			"/atomicNumber"
#define NUMBER_DENSITY_CMD			"/numberDensity"
#define RADIUS_CMD				"/radius"
#define THICKNESS_CMD				"/thickness"

#define GENERATE_CMD				"/generate"
#define ALPHA_CMD				"/alpha"
#define DELTA_CMD				"/delta"
#define ENERGY_CMD				"/energy"
#define THETA_CMD				"/theta"
#define DISTANCE_CMD				"/distance"
#define NUMBER_CMD				"/number"

#define ANALYSIS_CMD				"/analysis"
#define FILE_CMD				"/file"
#define	TITLE_CMD				"/title"
#define BINS_CMD				"/bins"
#define	MIN_CMD					"/min"
#define	MAX_CMD					"/max"

#define CUT_CMD					"/cuts"
#define LOW_ENERGY_CMD				"/setLowEdge"

#define RUN_CMD					"/run"
#define INIT_CMD				"/initialize"
#define BEAM_ON_CMD				"/beamOn"

#define CONTROL_CMD				"/control"
#define EXECUTE_CMD				"/execute"

#define MACRO_CMD				CONTROL_CMD	EXECUTE_CMD
#define ANALYSIS_FILE_CMD			ANALYSIS_CMD	FILE_CMD
#define WORLD_RADIUS_CMD			GEOMETRY_CMD	WORLD_CMD	RADIUS_CMD
#define DETECTOR_ATOMIC_NUMBER_CMD		GEOMETRY_CMD	DETECTOR_CMD	ATOMIC_NUMBER_CMD
#define DETECTOR_NUMBER_DENSITY_CMD		GEOMETRY_CMD	DETECTOR_CMD	NUMBER_DENSITY_CMD
#define DETECTOR_RADIUS_CMD			GEOMETRY_CMD	DETECTOR_CMD	RADIUS_CMD
#define DETECTOR_THICKNESS_CMD			GEOMETRY_CMD	DETECTOR_CMD	THICKNESS_CMD
#define GENERATE_ALPHA_ENERGY_CMD		GENERATE_CMD	ALPHA_CMD	ENERGY_CMD
#define GENERATE_ALPHA_DISTANCE_CMD		GENERATE_CMD	ALPHA_CMD	DISTANCE_CMD
#define ANALYSIS_ALPHA_ENERGY_TITLE_CMD		ANALYSIS_CMD	ALPHA_CMD	ENERGY_CMD	TITLE_CMD
#define ANALYSIS_ALPHA_ENERGY_BINS_CMD		ANALYSIS_CMD	ALPHA_CMD	ENERGY_CMD	BINS_CMD
#define ANALYSIS_ALPHA_ENERGY_MIN_CMD		ANALYSIS_CMD	ALPHA_CMD	ENERGY_CMD	MIN_CMD
#define ANALYSIS_ALPHA_ENERGY_MAX_CMD		ANALYSIS_CMD	ALPHA_CMD	ENERGY_CMD	MAX_CMD
#define ANALYSIS_ALPHA_THETA_TITLE_CMD		ANALYSIS_CMD	ALPHA_CMD	THETA_CMD	THETA_CMD
#define ANALYSIS_ALPHA_THETA_BINS_CMD		ANALYSIS_CMD	ALPHA_CMD	THETA_CMD	BINS_CMD
#define ANALYSIS_ALPHA_THETA_MIN_CMD		ANALYSIS_CMD	ALPHA_CMD	THETA_CMD	MIN_CMD
#define ANALYSIS_ALPHA_THETA_MAX_CMD		ANALYSIS_CMD	ALPHA_CMD	THETA_CMD	MAX_CMD
#define ANALYSIS_DELTAS_TITLE_CMD		ANALYSIS_CMD	DELTA_CMD	NUMBER_CMD	TITLE_CMD
#define ANALYSIS_DELTAS_BINS_CMD		ANALYSIS_CMD	DELTA_CMD	NUMBER_CMD	BINS_CMD
#define ANALYSIS_DELTAS_MIN_CMD			ANALYSIS_CMD	DELTA_CMD	NUMBER_CMD	MIN_CMD
#define ANALYSIS_DELTAS_MAX_CMD			ANALYSIS_CMD	DELTA_CMD	NUMBER_CMD	MAX_CMD
#define ANALYSIS_DELTA_ENERGY_TITLE_CMD		ANALYSIS_CMD	DELTA_CMD	ENERGY_CMD	TITLE_CMD
#define ANALYSIS_DELTA_ENERGY_BINS_CMD		ANALYSIS_CMD	DELTA_CMD	ENERGY_CMD	BINS_CMD
#define ANALYSIS_DELTA_ENERGY_MIN_CMD		ANALYSIS_CMD	DELTA_CMD	ENERGY_CMD	MIN_CMD
#define ANALYSIS_DELTA_ENERGY_MAX_CMD		ANALYSIS_CMD	DELTA_CMD	ENERGY_CMD	MAX_CMD
#define ANALYSIS_DELTA_THETA_TITLE_CMD		ANALYSIS_CMD	DELTA_CMD	THETA_CMD	THETA_CMD
#define ANALYSIS_DELTA_THETA_BINS_CMD		ANALYSIS_CMD	DELTA_CMD	THETA_CMD	BINS_CMD
#define ANALYSIS_DELTA_THETA_MIN_CMD		ANALYSIS_CMD	DELTA_CMD	THETA_CMD	MIN_CMD
#define ANALYSIS_DELTA_THETA_MAX_CMD		ANALYSIS_CMD	DELTA_CMD	THETA_CMD	MAX_CMD
#define CUT_LOW_ENERGY_CMD			CUT_CMD		LOW_ENERGY_CMD
#define RUN_SIMULATION_CMD			RUN_CMD		INIT_CMD  	NEW		RUN_CMD		BEAM_ON_CMD

#endif
